# Generated by Django 5.0.1 on 2025-12-12 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Bruno", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("llm_provider", models.CharField(default="openai", max_length=50)),
                ("model", models.CharField(default="gpt-4", max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2000)),
                (
                    "system_prompt",
                    models.TextField(default="You are Bruno, a helpful AI assistant."),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
