# Generated by Django 5.0.1 on 2025-12-13 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_single_conversation_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chat.note')),
            ],
            options={
                'verbose_name_plural': 'Note entries',
                'db_table': 'note_entries',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='notes_user_id_e4f281_idx'),
        ),
        migrations.AddIndex(
            model_name='noteentry',
            index=models.Index(fields=['note', 'position'], name='note_entrie_note_id_274f72_idx'),
        ),
    ]
