# Generated by Django 5.0.1 on 2025-12-13 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_note_noteentry_note_notes_user_id_e4f281_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('personal', 'Personal Information'), ('preference', 'Preference'), ('relationship', 'Relationship'), ('goal', 'Goal/Aspiration'), ('experience', 'Past Experience'), ('skill', 'Skill/Ability'), ('fact', 'General Fact')], default='fact', max_length=20)),
                ('key', models.CharField(help_text='Memory key/topic (e.g., "favorite_food", "hometown")', max_length=200)),
                ('value', models.TextField(help_text='The actual memory content')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1')),
                ('importance', models.IntegerField(default=5, help_text='Importance score 1-10')),
                ('first_mentioned', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('source_message_id', models.UUIDField(blank=True, help_text='Message that created this memory', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_memories',
                'ordering': ['-importance', '-last_accessed'],
                'indexes': [models.Index(fields=['user', 'memory_type'], name='user_memori_user_id_bebb74_idx'), models.Index(fields=['user', '-importance'], name='user_memori_user_id_0caff4_idx'), models.Index(fields=['user', 'key'], name='user_memori_user_id_d009c7_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
